dist: bionic
language: go
go:
  - 1.13.3
services:
  - docker
before_script:
  - docker pull boxfuse/flyway
  - export GOROOT=$(go env GOROOT)
  - db/postgres-start.sh
go_import_path: github.com/adevinta/vulcan-scan-engine
install: _script/bootstrap
script: _script/cibuild
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
