dist: bionic
language: go
env:
  global:
    - FLYWAY_VERSION=9.19.3
    - INPUT_BUILDARGS=FLYWAY_VERSION=$FLYWAY_VERSION
    - INPUT_PLATFORM=linux/amd64  # ,linux/arm64
go:
  - 1.21.x
services:
  - docker
before_script:
  - export GOROOT=$(go env GOROOT)
  - db/postgres-start.sh
go_import_path: github.com/adevinta/vulcan-scan-engine
script:
  - go install -v $(go list ./... | grep -v /vendor/)
  - go test -short -v $(go list ./... | grep -v /vendor/)
  - cd cmd/vulcan-scan-engine && go build && cd ../..
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/buildx.sh)'
